Repository open-policy-agent/conftest, pull requests merged in 2019-11, with the labels that each got.

#146 Add explicit WORKDIR to Docker image
  Dockerfile
Labels: bug

#143 Handle explicitly blank filenames passed into conftest
  acceptance.bats
  commands/test/test.go
Labels: bug

#134 Test package refactor
  commands/commands.go
  commands/test/fake_output_manager.go
  commands/test/test.go
  commands/test/test_test.go
Labels: refactoring

#147 Update modules and fix push pathing
  commands/push/push.go
  go.mod
  go.sum
  policy/policy.go
Labels: bug

#148 Remove yaml unmarshalling
  commands/test/test.go
  parser/cue/cue.go
  parser/cue/cue_test.go
  parser/docker/docker.go
  parser/hcl2/hcl2.go
  parser/ini/ini.go
  parser/parser.go
  parser/parser_test.go
  parser/terraform/terraform.go
  parser/toml/toml.go
  parser/yaml/yaml.go
Labels: refactoring

#131 Verify package refactor
  commands/commands.go
  commands/test/output.go
  commands/test/test.go
  commands/verify/verify.go
Labels: refactoring

#150 Build rpm and deb packages for Linux users of conftest
  .goreleaser.yml
Labels: enhancement

#160 Move commands to internal
  .goreleaser.yml
  internal/commands/default.go
  internal/commands/output.go
  internal/commands/output_test.go
  internal/commands/parse.go
  internal/commands/parse_test.go
  internal/commands/pull.go
  internal/commands/pull_test.go
  internal/commands/push.go
  internal/commands/test.go
  internal/commands/test_test.go
  internal/commands/update.go
  internal/commands/verify.go
  main.go
Labels: refactoring
