Repository open-policy-agent/conftest, pull requests merged in 2019-10, with the labels that each got.

#109 Shorten combine-config flag to combine
  README.md
  acceptance.bats
  pkg/commands/test/test.go
  pkg/commands/test/test_test.go
Labels: enhancement

#110 Fix incorrect exit code
  acceptance.bats
  pkg/commands/test/test.go
Labels: bug

#121 Use relative path on compiling policies
  acceptance.bats
  examples/nested/data.json
  examples/nested/policy/group1/main.rego
  examples/nested/policy/group2/main.rego
  pkg/policy/compiler.go
Labels: bug

#122 Remove the constants package
  .goreleaser.yml
  pkg/commands/commands.go
  pkg/commands/parse/parse.go
  pkg/commands/push/push.go
  pkg/commands/test/test.go
  pkg/commands/verify/verify.go
  pkg/constants/constants.go
Labels: refactoring

#123 Simplify module file
  go.mod
  go.sum
Labels: refactoring

#115 Remove pkg folder
  .goreleaser.yml
  cmd/main.go
  commands/commands.go
  commands/parse/parse.go
  commands/parse/parse_test.go
  commands/parse/testdata/dummy-deploy.yaml
  commands/parse/testdata/grafana.ini
  commands/parse/testdata/terraform.tf
  commands/parse/testdata/traefik.toml
  commands/pull/pull.go
  commands/pull/pull_test.go
  commands/push/push.go
  commands/test/fake_output_manager.go
  commands/test/output.go
  commands/test/output_test.go
  commands/test/test.go
  commands/test/test_test.go
  commands/test/testdata/deployment+service.yaml
  commands/test/testdata/deployment.asdfasdfasdf
  commands/test/testdata/deployment.yaml
  commands/test/testdata/policy/test_policy.rego
  commands/test/testdata/policy/test_policy_dockerfile.rego
  commands/test/testdata/policy/test_policy_multifile.rego
  commands/update/update.go
  commands/verify/verify.go
  parser/cue/cue.go
  parser/cue/cue_test.go
  parser/docker/docker.go
  parser/docker/docker_test.go
  parser/hcl2/convert.go
  parser/hcl2/convert_test.go
  parser/hcl2/hcl2.go
  parser/ini/ini.go
  parser/ini/ini_test.go
  parser/parser.go
  parser/parser_test.go
  parser/terraform/terraform.go
  parser/terraform/terraform_test.go
  parser/terraform/testdata/sample.tf
  parser/toml/toml.go
  parser/yaml/yaml.go
  parser/yaml/yaml_test.go
  policy/compiler.go
  policy/policy.go
  policy/policy_test.go
Labels: refactoring

#119 Dockerfile fix
  Dockerfile
  Makefile
Labels: bug

#124 Policy package refactor
  commands/pull/pull.go
  commands/test/test.go
  commands/test/test_test.go
  commands/update/update.go
  commands/verify/verify.go
  policy/compiler.go
  policy/policy.go
Labels: refactoring

#135 Remove viper dependency on Download
  commands/commands.go
  commands/pull/pull.go
  commands/pull/pull_test.go
  commands/test/test.go
  commands/update/update.go
  policy/policy.go
Labels: refactoring

#132 Refactor parse command: more strict tests for controlling output and printing filename
  commands/commands.go
  commands/parse/parse.go
  commands/parse/parse_test.go
Labels: refactoring

#140 Fix kubernetes policy example
  examples/kubernetes/policy/base_test.rego
  examples/kubernetes/policy/deny.rego
Labels: bug

#139 Remove auth/oras from notes
  README.md
Labels: documentation

#144 Lowercase keys in JSON output
  commands/test/output.go
  commands/test/output_test.go
Labels: enhancement
